[[main]]
  name = "首页"
  pageRef = "/"
  weight = 10

[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "计算器"
  url = "/tools/yysls-graduation/"
  weight = 35

[[main]]
  name = "装备库"
  url = "/tools/yysls-armory/"
  weight = 36

[[main]]
  name = "搭配器"
  url = "/tools/yysls-outfitter/"
  weight = 37

[[footer]]
  name = "文章"
  pageRef = "posts"
  weight = 10

[[footer]]
  name = "标签"
  pageRef = "tags"
  weight = 20
